const LEVELLISTE = [
	{	
		"map": [
			'                                                                                                                                                ',
            '                              C                                                                                                                 ',
            '                              C                                                                                                                 ',
            '                             SC                                                                                                                 ',
            '                        DDDDDD                                                                                                                  ',
            '                                                                                                                                                ',
            '                     DD                                                                                                                         ',
            '                                                                                                                                                ',
            '               DD                                                                                                                               ',
            '                                                                                                                                                ',
            '                    DD                                                                                                                          ',
            '                                                                                                                                                ',
            '                         DD                                                                                                                     ',
            '                                                                                                                                                ',
            '                             DD                                                                                                                 ',
            '                                                                                                                                                ',
            '                                    AAA                                             AAA                                             AAA         ',
            '                                    A A                                             A A                                             A A         ',
			'   AAAAA                 AAAAA  CC  A A             AAAA                 AAAAA  CC  A A             AAAA                 AAAAA  CC  A A         ',
			'   A   A     AAAA        A   A      A A            AAAAA    AAAAA        A   A      A A            A   A    AAAAA        A   A      A A         ',
			'  A    A    A    AA  CC  A   A      A A           AA   A   AA    A   CC  A   A      A A           A    A   A     A   CC  A   A      A A         ',
			'  A    A  AA      A      A   A      A A   AAAA    AA   A   A      A      A   A      A A   AAAA    A    A  A       A      A   A      A A   AAAADD',
			'  A    A  A       A      A   A      A A   A  AA   A    A  A       A      A   A      A A   A AAA   A    A  A       A      A   A      A A   A  A  ',
            'AAAA   A  A       A      A   A      A A   A  A AAAA    A  A       A      A   A      A A   A A AAAA     A  A       A      A   A      A A   A  A  ',
            '       A  A       A      A   A      A A   A  A         A  A       A      A   A      A A   A A          A  A       A      A   A      A A   A   AA',
            '       A  A       A      A   A      A A   A  A         A  A       A      A   A      A A   A A          A  A       A      A   A      A A   A    A',
            'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'
		] ,
		"startX": 150 ,
		"startY": 500 ,
		"startX1": 350 ,
		"startY1": 700 ,
		"hintergrund": "lvl1.1",
		"tileset": "Tileset",
		"spritesheet": "Spritesheet",
		"musik": "Musik1"
	} ,
	{	
		"map": [
			'                                                                                                ',
			'                                                                                                ',
			'                                        C                                                       ',
			'                                        C                                                       ',
			'                                        C1             C                                        ',
			'                                        DDDDDDD        C                                        ',
			'                                                     DD                                         ',
			'                                                                                                ',
			'                                              DD       C                                        ',
			'                                                       C                                        ',
			'                                                     DD                                         ',
			'                                                                                                ',
			'                                                DD                                              ',
			'                                                                                                ',
			'                                          DD                                                    ',
			'                                                                                                ',
			'                                    EEE                                             EEE         ',
			'                                    E E                                             E E         ',
			'   EEEEE                 EEEEE  CC  E E             EEEE                 EEEEE  CC  E E         ',
			'   E   E     EEEE        EE  E      E E            EEE E    EEEEE        E   E      E E         ',
			'  E    E    EEEEEEE  CC  EE  E      E E           EE   E   EE    E   CC  E   E      E E         ',
			'  E    E  EE    E E      EEEEE      E E   EEEE    EE   E   E      E      E   E      E E   EEEEDD',
			'  E    E  E     E E      EEEEE      E E   E  EE   E    E  E       E      E   E      E E   E EEE ',
			'EEEE   E  E       E      EEEEE      E E   E  E EEEE    E  E       E      E   E      E E   E E EE',
			'       E  E       E      EEEEE      EEE   E  E         E  E       E      E   E      E E   E E   ',
			'       E  E       E      EEEEE      E E   E  E         E  E       E      E   E      E E   E E   ',
			'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'
		] ,
		"startX": 150 ,
		"startY": 500 ,
		"hintergrund": "lvl1.2",
		"tileset": "Tileset",
		"spritesheet": "Spritesheet",
		"musik": "Musik2"
	},
	{	
		"map": [
			'                                                                                                                                                                   ',
            '                                                                                                                                                                   ',
            '                                                                                                                                                                   ',
            '                                                         C                                                                                                         ',
            '                                                         C                                                                                                         ',
            '                                                         C2                                                                                                        ',
            '                                                         DDDDDD                                                                                                      ',
            '                                                                                                                                                                   ',
            '                                                                  DDDD                                                                                               ',
            '                                                                                                                                                                   ',
            '                                                                          DDDDD                                                                                     ',
            '                                                                                                                                                                   ',
            '                                                                     DD                                                                                            ',
            '                                                                                                                                                                   ',
            '                                                               DD                                                                                                  ',
            '                                                                                                                                                                   ',
            '                                    GGG                  DD                         GGG                                                                            ',
            '                                    G G                                             G G                                                                            ',
			'   GGGGG                 GGGGG  CC  G G             GGGG                 GGGGG  CC  G G             GGGG                 GGGGG                                     ',
			'   G   G     GGGG        GG  G      G G            GGG G    GGGGG        G   G      G G            G   G    GGGGG        G   G                              GGGGG  ',
			'  G    G    GGGGGGG  CC  GG  G      G G           GG   G   GG    G   CC  G   G      G G           G    G   G     G   CC  G   G                             G     G ',
			'  G    G  GG    G G      GGGGG      G G   GGGG    GG   G   G      G      G   G      G G   GGGG    G    G  G       G      G   G                            G       G',
			'  G    G  G     G G      GGGGG      G G   G  GG   G    G  G       G      G   G      G G   G GGG   G    G  G       G      G   G                            G       G',
            'GGG    G  G       G      GGGGG      G G   G  G GGGG    G  G       G      G   G      G G   G G GGGG     G  G       G      G   G                            G       G',
            '       G  G       G      GGGGG      GGG   G  G         G  G       G      G   G      G G   G G          G  G       G      G   G                                    G',
            '       G  G       G      GGGGG      G G   G  G         G  G       G      G   G      G G   G G          G  G       G      G   G                                    G',
            'HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH'
			] ,
			"startX": 150 ,
			"startY": 500 ,
			"hintergrund": "lvl1.3",
			"tileset": "Tileset",
			"spritesheet": "Spritesheet",
			"musik": "Musik2"
	},	
	{	
	"map": [
		'                                                                                                                                                ',
		'                                                                                                                                                ',
		'                                                                                                                                                ',
		'                                                                                                                                                ',
		'                                                                                                                                                ',
		'                                                                                                                                                ',
		'                                                                                                                                                ',
		'                                                                                                                                                ',
		'                                                                                                                                                ',
		'                                       KK                                                                                                       ',
		'                                                                                                                                                ',
		'                                  KK                                                                                                            ',
		'                                                                                                                                                ',
		'                            KK                                                                                                                  ',
		'                                                                                                                     C                          ',
		'                       KK                                               KK               KK              KK          C                          ',
		'                                                                                                                   3 C                          ',
		'LLLLLLLLLLLLLLLLLLLLLLLLLLIIIIIIIIIIIIIIIIIILLLLLLLLLLLLL    LLLLLLLLLIIIIIILLLLLLLLLLIIIIIIIILLLLLLLLIIIIIIIILLLLLLLLLLLLL      LLLLLLLLLLLLLLL',
		'                                                        M                                                                       LM              ',
		'                                                        M                                                                      L M              ',
		'                                                        M                                                                       M               ',
		'                                                        M                                                                  LL   M               ',
		'                                                        M                                       LL                              M               ',
		'                                                        M                                LL                             LL      M               ',
		'                                                        M              LL          LL                  LL                       M               ',
		'                                                        MLLLL    LL          LL                                     LL          M               ',
		'                                                        M                                                    LL                 M               ',
		'LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIILLLLLLLLLLLLLLLLLLLLLLLLLLLL'
		] ,
		"startX": 40 ,
		"startY": 500 ,
		"hintergrund": "lvl2",
		"tileset": "Tileset",
		"spritesheet": "Spritesheet2",
		"musik": "Musik2"
	},
	{	
		"map": [
		'                                                                                                                           J                    ',
		'                                                                                                                           J                    ',
		'                                                                                                                           J                    ',
		'                                                                                                                           J                    ',
		'                                                                                                                           J                    ',
		'                                                                                                                           J                    ',
		'                                                                         JJ       JJ       JJ       JJ                     J  X                 ',
		'                                                                                  JJ           JJ   JJJ                    JJJJJJJJJJ           ',
		'                                                                  JJ              JJ                JJ                                  JJ      ',
		'                                                                                  JJ                JJ J                                        ',
		'                                                            JJ                    JJ  JJ        JJ  JJ                                        JJ',
		'                                                    JJ                            JJ                JJ  J                                       ',
		'             JJ       JJ                                                          JJ        JJ      JJ                                          ',
		'     JJ                       JJ               JJ                                 JJ                JJ   J                                      ',
		'   JJJJIIIIIIIIIIIIIIIIIIIIIIIJJJJ           JJJJIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIJJIIIIIIIIIIIIIIIIJJ                        Y         JJ      ',
		'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ77777JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
		'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ     JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ',
		'                                    JJ    J                                       JJ                                                            ',
		'                                    J    JJ                                       JJ                                                            ',
		'                                    J     J                                       JJ                                                            ',
		'                                    JJ    J                      JJ               JJ                                                            ',
		'                                    J     J                JJ         JJ          JJ                                                            ',
		'                                    J    JJ                               JJ      JJ                                                            ',
		'                                    J     J           JJ                  JJJ     JJ                                                            ',
		'                                    JJ           JJ                       JJ                     JJ       JJ       JJ                           ',
		'                                    J          JJJJIIIIIIIIIIIIIIIIIIIIIIIJJ J              JJJJIIIIIIIIIIIIIIIIIIIIIIIJJ                    V  ',
		'JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ'
		] ,
		"startX": 40 ,
		"startY": 550 ,
		"hintergrund": "lvl3",
		"tileset": "Tileset",
		"spritesheet": "Spritesheet2",
		"musik": "Musik2"
}
]